### ISSUE TITLE
Design, UbiquiBar: Apron Logo + Name Tag

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/sponsorships#4]

**Comment by 0x4007** [comment]
@diamondnegroni can you please post [ English name ] | [ Korean name ] here for everybody as a final confirmation?

**Comment by diamondnegroni** [comment]
안제민 l  Jemin
정호빈 l  Ho Bin
이종훈 l  Jong Hoon
윤주영 I  Ju Young
김동하 I  Dong Ha

**Comment by 0x4007** [comment]
I think they should all be full name in korean then so "Jung Ho Bin" can you confirm the spelling and edit your post?

**Comment by diamondnegroni** [comment]
정호빈

**Comment by 0x4007** [comment]
# All Stars

![nametag-hobin](https://github.com/ubiquity/.github/assets/4975670/8d832019-4b8b-474c-8745-08d783e79946)
![nametag-jemin](https://github.com/ubiquity/.github/assets/4975670/94363e1f-342d-485d-ae28-5cfc969637aa)
![nametag-jonghoon](https://github.com/ubiquity/.github/assets/4975670/bbe1ea43-6e67-497b-9141-b2f440432c97)
![nametag-juyoung](https://github.com/ubiquity/.github/assets/4975670/76333379-fd37-4728-a0d7-85d459ec61cf)
![nametag-dongha](https://github.com/ubiquity/.github/assets/4975670/2e081b36-40c0-47f7-bc9e-de1e8a95c3bb)

# Support

![nametag-sujeong](https://github.com/ubiquity/.github/assets/4975670/92816350-f3f6-4248-b889-b6670097d4e1)
![nametag-alexander](https://github.com/ubiquity/.github/assets/4975670/a624cf94-4fb5-4c6a-b50c-ed9cb37d0a53)

**Comment by diamondnegroni** [comment]
Thanks !
